name: Update Issue Status

on:
  pull_request:
    branches:
      - "*"

jobs:
  update_issue_status:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch name contains issue number
        uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: ${{github.repository}}
          column: Backlog
          repo-token: ${{ secrets.GITHUB_TOKEN }}
