name: Update Issue Status

on:
  pull_request:
    branches:
      - "*"

jobs:
  update_issue_status:
    runs-on: ubuntu-latest
    steps:
      - run: echo ::set-env name=GHA_BRANCH::$(echo $GITHUB_REF | awk -F / '{print $3}')
      - name: Check if branch name contains issue number
        uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: ${{ github.event.repository.name }}
          column: In Progress
          repo-token: ${{ secrets.PERSIONAL_ACCESS_TOKEN }}
